# Checkout your repository
- uses: actions/checkout@v2
  with:
    fetch-depth: 2
- run: git checkout HEAD^

# Cache Unity Library folder

# Configure test job

# Configure build job
- uses: game-ci/unity-builder@<version>
  env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  with:
    projectPath: path/to/your/project
    unityVersion: 2019.4.19f1
    targetPlatform: Android

# Deploy application
